lib/media_radar_web/router.ex
defmodule MediaRadarWeb.Router do
  use MediaRadarWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MediaRadarWeb do
    pipe_through :browser # Use the default browser stack

    get  "/", SongController, :index

    resources "/blogs", BlogController, only: ~w(index)a do
      resources "/media", SongController, only: ~w(index)a
    end

    resources "/media", SongController, only: ~w(index)a
  end

  # Other scopes may use custom stacks.
  # scope "/api", MediaRadarWeb do
  #   pipe_through :api
  # end
end

lib/media_radar/blog.ex
defmodule MediaRadar.Blog do
  use Ecto.Schema
  import Ecto.Changeset
  alias MediaRadar.{Blog, Song, Post}


  schema "blogs" do
    field :country, :string
    field :feed_url, :string
    field :logo_url, :string
    field :name, :string

    many_to_many :songs, Song, join_through: Post

    timestamps()
  end

  @doc false
  def changeset(%Blog{} = blog, attrs) do
    blog
    |> cast(attrs, [:feed_url, :name, :country, :logo_url])
    |> validate_required([:name, :feed_url])
    |> unique_constraint(:name)
    |> unique_constraint(:feed_url)
    |> unique_constraint(:logo_url)
  end
end

lib/media_radar_web/controllers/blog_controller.ex
defmodule MediaRadarWeb.BlogController do
  alias MediaRadar.{Blog, Repo}
  use MediaRadarWeb, :controller

  def index(conn, _params) do
    render conn, "index.html", blogs: Repo.all(Blog)
  end
end

lib/media_radar_web/views/blog_view.ex
defmodule MediaRadarWeb.BlogView do
  use MediaRadarWeb, :view

  # TODO: dont like this, but this is the only way to translate the
  # country code, the idea of the codes was to translate them to english
  # if necessary, but since we use only spanish maybe we should just use
  # the country name directly
  defimpl Phoenix.HTML.Safe, for: Countriex.Country do
    def to_iodata(country_data) do
      case country_data.name do
        "Spain" -> "España"
        "Venezuela, Bolivarian Republic of" -> "Venezuela"
        country_name -> country_name
      end
    end
  end

  def full_country_name(country_code) do
    Countriex.get_by(:alpha2, country_code)
  end
end

lib/media_radar_web/templates/blog/_blog.html.eex
<div class="tile blog is-parent is-4">
  <div class="tile is-child notification is-light">
    <p class="title title-link">
      <%= link @blog.name, to: blog_song_path(@conn, :index, @blog.id), class: "title title-link" %>
    </p>


    <p class="subtitle"><%= if (is_nil(@blog.country) || String.trim(@blog.country) == ""), do: "Varios Paises", else: full_country_name(@blog.country) %></p>
    <figure class="image">
      <% default_image_path = static_path(@conn, "/images/blog-default.jpg") %>
      <%= img_tag (@blog.logo_url || default_image_path), onerror: ~s(this.error=null;this.src="#{default_image_path}") %>
    </figure>
  </div>
</div>

lib/media_radar_web/templates/blog/index.html.eex
<h2>Indexed Blogs</h2>

<div class="tile is-ancestor is-multiline columns">
  <%= for blog <- @blogs do %>
    <%= render MediaRadarWeb.BlogView, "_blog.html", blog: blog, conn: @conn %>
  <% end %>
</div